### ISSUE TITLE
Tooling - move content and remove page?

### ISSUE THREAD

**Issue by Grand-Thibault** [catenax-eV/catenax-ev.github.io#2]
The page provides currently limited value. The tools should be descriped elsewhere:
- Team --> Com. + EG
- GitHub --> should be split in Tractus-X (link to T-X page) and Com. + EG.
- Eclipse Tooling --> already described on T-X page, add link to T-X role description
- Testtool --> add to general test mgmt. description?

**Comment by mihahnberlin** [comment]
The other way round - we wanted to describe the tools in one place so that it is clear what is available and what it is basically there for. They can then simply be "used" in the individual chapters.
