### ISSUE TITLE
Working model: feedback to Test Management section

### ISSUE THREAD

**Issue by ghost** [catenax-eV/catenax-ev.github.io#26]
TM intro: The software testing of reference implementations is sponsored and coordinated by the Catena-X association.
IMHO this is incorrect:
If at all, only some portion of the e2e release tests should be coordinated by the association. Previous levels should be covered in "daily business" with Tractus-X; based on open source best practices.

**Comment by Grand-Thibault** [comment]
@RolaH1t is this issue still relevant? If yes, please do the required changes in the WM and create a PR. If no, please close the issue.
