### ISSUE TITLE
Open Planning and Standard Planning

### ISSUE THREAD

**Issue by stephanbcbauer** [catenax-eV/catenax-ev.github.io#3]
## Description

Preparation for the open planning is done via feature proposals and refinement. For standard requests there is a special tool called Houston, but this not for planning. This tool is for concrete requests.

For the standard planning (parallel to open planning) a documentation/description is needed “how the planning should be done” and “how is the standard planning mapped to open planning” in case of issues.

## Proposal

The standard planning could also be handled like we do in open planning with a sig-release repository. We could use a sig-release repository in the catenax-ev GitHub organization to **plan** the standards in a public issue list. Issues mapped to releases/milestones.

In this case, we would have a transparent overview. The Standard issue (maybe just a headline) could also be mapped/linked to an open-source feature.

**Comment by Grand-Thibault** [comment]
done
