### ISSUE TITLE
[BUG] Possible incorrect naming of abbreviation in glossary

### ISSUE THREAD

**Issue by matbmoser** [catenax-eV/catenax-ev.github.io#4]
# Introduction
I was checking the  glossary at this page: https://catenax-ev.github.io/docs/operating-model/glossary and detected a possible typo:

![image](https://github.com/catenax-eV/catenax-ev.github.io/assets/71728767/8a21783f-f6ed-44ee-9fcf-112f2a2f0c0b)

And I realized the EDC abbreviation is based on the Eclipse Project Name and not on the Connector itself.
For not causing confusion in Catena-X always when we refer to EDC we are referring to "Eclipse Data Space Connector".

Maybe is correct but I would say instead of telling as `EDC = Eclipse Data Space Components`  I would tell as `EDC = Eclipse Data Space Connector`. 

# Possible Solutions:
## Where is the problem
https://github.com/catenax-eV/catenax-ev.github.io/blob/f75371664c0dfdbcabb2c66e027e2215a763cdb7/docs/operating-model/glossary/glossary.md?plain=1#L22

## How it should look
```md
| EDC                   | Eclipse Data Space Connector                                              |
```

I could create a PR with the solution, but if it is correct then we don't need to do anything

> [!TIP]
>
> Creating this issue to proof the process ;) Nothing urgent...

**Comment by werner-roman** [comment]
Thanks a lot for rasing the topic and also testing the process! :) - we will take it up!

FYI - @catenax-eV/cx-team-operating-model

**Comment by hschwabe** [comment]
[like]  Henning Schwabe reacted to your message:
________________________________
From: Roman Werner ***@***.***>
Sent: Thursday, April 4, 2024 5:18:47 PM
To: catenax-eV/catenax-ev.github.io ***@***.***>
Cc: Henning Schwabe ***@***.***>; Team mention ***@***.***>
Subject: [EXT] Re: [catenax-eV/catenax-ev.github.io] [BUG] Possible incorrect naming of abbreviation in glossary (Issue #4)


Thanks a lot for rasing the topic and also testing the process! :) - we will take it up!

FYI - @catenax-eV/cx-team-operating-model<https://github.com/orgs/catenax-eV/teams/cx-team-operating-model>

**Comment by HFocken** [comment]
AFAIK, Eclipse Data Space Components is the correct term - it used to be just the connector, but since then has expanded and includes more "components" than just the connector. Can be closed.
