### ISSUE TITLE
Migrate Releasemanagement presentation to Markdown

### ISSUE THREAD

**Issue by stephanbcbauer** [catenax-eV/catenax-ev.github.io#53]
PPT is already there

**Comment by stephanbcbauer** [comment]
@HFocken  there are a lot of information in the ppt. For me, it's a bit unclear, what should be added to the Working model. And where is the single source of truth?

**Comment by HFocken** [comment]
I tried to explain that in the Email - the PPT should not be added to a markdown file and not be included in the Working Model as the target group is different - this is an internal document for our Association team. PPT also bc. some are not using Github (yet).

**Comment by HFocken** [comment]
See comment above.

**Comment by HFocken** [comment]
See comment above.

**Comment by HFocken** [comment]
See comment above.
