### ISSUE TITLE
Handling of different feature types

### ISSUE THREAD

**Issue by stephanbcbauer** [catenax-eV/catenax-ev.github.io#6]
## Why

During the open planning 24.08 we had different types of features

- concepts/whitepapers
- kits
- development

Each of them has to be handled individually because the entry criteria are different. Definitely, for a development feature all the dependencies need to be clear, but for example for a concept it's not the case. Of course, it would be nice to know all the dependencies, but this is also the goal of a concept… to identify the dependencies.

For kits for example, it seems there is no need for a dedicated committer, cause right now still Max and Daniel are somehow responsible. At least in the planning, this was enough.

## What

I think we have to describe the different types and what is expected.

**Comment by Grand-Thibault** [comment]
duplicate
