### ISSUE TITLE
Standard Library redirect incomplete

### ISSUE THREAD

**Issue by ClosedSourcerer** [catenax-eV/catenax-ev.github.io#61]
https://catena-x.net/de/standard-library redirects to https://catenax-ev.github.io/docs/next/standards/overview

https://catena-x.net/en/standard-library does not redirect

**Comment by jSchuetz88** [comment]
Thank you for your feedback, will be fixed today.

**Comment by jSchuetz88** [comment]
On the client side, it may be necessary to empty the cache, but the redirection is in place.
