### ISSUE TITLE
CX-0029-ProductCarbonFootprintRulebook: missing PDF link

### ISSUE THREAD

**Issue by VladimirAlexiev** [catenax-eV/catenax-ev.github.io#99]
Look at https://catenax-ev.github.io/docs/next/standards/CX-0029-ProductCarbonFootprintRulebook.
It is quite un-informative.

The source is at https://github.com/catenax-eV/catenax-ev.github.io/blob/main/docs/standards/CX-0029-ProductCarbonFootprintRulebook/CX-0029-ProductCarbonFootprintRulebook.md:

>Note 1: Only available as a PDF-File
> As CX-0029 has been re-classified as a *non-technical requirement*
> **Link to the new Version**: [NFR-PCF-Rulebook v3.0](http://localhost:3000/docs/next/non-functional/overview)

This link is broken (localhost). Perhaps until this reorganization is completed, link to the older version:
https://github.com/catenax-eV/catenax-ev.github.io/blob/main/docs/standards/CX-0029-ProductCarbonFootprintRulebook/assets/CX-0029-ProductCarbonFootprintRulebook-v2.0.0.pdf

**Comment by jSchuetz88** [comment]
Hi @VladimirAlexiev,

thank you for your raising this issue. The link has been corrected.
